=pod

=head1 NAME

 CMP_certConf_new,
 CMP_ckuann_new,
 CMP_cr_new,
 CMP_genm_new,
 CMP_ir_new,
 CMP_kur_new	

=head1 SYNOPSIS

 #include <openssl/cmp.h>

 CMP_PKIMESSAGE * CMP_ir_new( CMP_CTX *ctx);
 CMP_PKIMESSAGE * CMP_cr_new( CMP_CTX *ctx);
 CMP_PKIMESSAGE * CMP_kur_new( CMP_CTX *ctx);
 CMP_PKIMESSAGE * CMP_certConf_new( CMP_CTX *ctx);
 CMP_PKIMESSAGE * CMP_genm_new( CMP_CTX *ctx);
 CMP_PKIMESSAGE * CMP_ckuann_new( const X509 *oldCaCert, const EVP_PKEY *oldPkey, const X509 *newCaCert, const EVP_PKEY *newPkey);

=head1 DESCRIPTION

This is the API for creating different CMP related PKIMESSAGES. The functions allocate a new message and fill it with the relevant data from the given CMP_CTX.

CMP_ir_new() creates an Initial Request message.

CMP_cr_new() creates a Certificate Request message.

CMP_kur_new() creates a Key Update Request message.

CMP_certConf_new() creates a Certificate Confirmation message.

CMP_genm_new() creates a new General Message.

CMP_ckuann_new() creates a new CA Key Update Announcement message.

=head1 NOTES

CMP is defined in RFC 4210 (and CRMF in RFC 4211).

The implementation of CMP for OpenSSL is still work in progress. The API might change every release!

=head1 RETURN VALUES

All of the functions return a new CMP_PKIMESSAGE structure containing the generated message.

=head1 EXAMPLE


=head1 TODO

A lot!

=head1 SEE ALSO

CMP_CTX, CMP_session, CMP_http
